[web]
<EC2_PUBLIC_IP>

[web:vars]
ansible_user=ubuntu
ansible_connection=ssh
ansible_ssh_private_key_file=~/.ssh/id_rsa_epicbook
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
ansible_remote_tmp=/tmp/ansible-tmp
db_host=<RDS_ENDPOINT>